# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hw2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 1200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(5, 10, 285, 500))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_01 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_01.setGeometry(QtCore.QRect(55, 140, 181, 51))
        self.pushButton_01.setObjectName("pushButton_01")
        self.pushButton_02 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_02.setGeometry(QtCore.QRect(55, 219, 181, 51))
        self.pushButton_02.setObjectName("pushButton_02")
        self.pushButton_03 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_03.setGeometry(QtCore.QRect(55, 300, 181, 51))
        self.pushButton_03.setObjectName("pushButton_03")

        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(305, 10, 285, 500))
        self.groupBox_1.setObjectName("groupBox_1")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_11.setGeometry(QtCore.QRect(50, 50, 181, 51))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_12.setGeometry(QtCore.QRect(50, 120, 181, 51))
        self.pushButton_12.setObjectName("pushButton_12")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_1)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 195, 245, 150))
        self.groupBox_13.setObjectName("groupBox_13")
        self.label = QtWidgets.QLabel(self.groupBox_13)
        self.label.setGeometry(QtCore.QRect(30, 15, 111, 41))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_13)
        self.comboBox.setGeometry(QtCore.QRect(30, 55, 79, 23))
        self.comboBox.setMaxVisibleItems(15)
        self.comboBox.setObjectName("comboBox")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_13.setGeometry(QtCore.QRect(30, 87, 181, 51))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_14.setGeometry(QtCore.QRect(50, 370, 181, 51))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton_15.setGeometry(QtCore.QRect(50, 441, 181, 51))
        self.pushButton_15.setObjectName("pushButton_15")

        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(605, 10, 285, 500))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textbox = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox.setGeometry(QtCore.QRect(50, 140, 201, 31))
        self.textbox.setObjectName("textbox")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_21.setGeometry(QtCore.QRect(50, 210, 201, 51))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_22.setGeometry(QtCore.QRect(50, 300, 201, 51))
        self.pushButton_22.setObjectName("pushButton_22")
        
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(905, 10, 285, 500))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_31.setGeometry(QtCore.QRect(60, 250, 181, 51))
        self.pushButton_31.setObjectName("pushButton_31")

        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(305, 510, 285, 500))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_41 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_41.setGeometry(QtCore.QRect(50, 60, 181, 51))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_42.setGeometry(QtCore.QRect(50, 150, 181, 51))
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_43.setGeometry(QtCore.QRect(50, 240, 181, 51))
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_44.setGeometry(QtCore.QRect(50, 330, 181, 51))
        self.pushButton_44.setObjectName("pushButton_44")

        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(605, 510, 285, 500))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_50 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_50.setGeometry(QtCore.QRect(50, 60, 190, 51))
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_51 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_51.setGeometry(QtCore.QRect(50, 120, 190, 51))
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_52 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_52.setGeometry(QtCore.QRect(50, 180, 190, 51))
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_53 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_53.setGeometry(QtCore.QRect(50, 240, 190, 51))
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_54 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_54.setGeometry(QtCore.QRect(50, 300, 190, 51))
        self.pushButton_54.setObjectName("pushButton_54")
        

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow-cvdlhw1"))
        self.groupBox.setTitle(_translate("MainWindow", "Load Image"))
        self.pushButton_01.setText(_translate("MainWindow", "Load Folder"))
        self.pushButton_02.setText(_translate("MainWindow", "Load Image_L"))
        self.pushButton_03.setText(_translate("MainWindow", "Load Image_R"))
        
        self.groupBox_1.setTitle(_translate("MainWindow", "1. Calibration"))
        self.label.setText(_translate("MainWindow", "Select Image"))
        self.pushButton_11.setText(_translate("MainWindow", "1.1 Find Corners"))
        self.pushButton_12.setText(_translate("MainWindow", "1.2 Find Intrinsic"))
        self.groupBox_13.setTitle(_translate("MainWindow", "1.3 Find Extrinsic"))
        self.pushButton_13.setText(_translate("MainWindow", "1.3 Find Extrinsic"))
        self.pushButton_14.setText(_translate("MainWindow", "1.4 Find Distortion"))
        self.pushButton_15.setText(_translate("MainWindow", "1.5 Show Result"))

        self.groupBox_2.setTitle(_translate("MainWindow", "2. Augumented Reality"))
        self.pushButton_21.setText(_translate("MainWindow", "2.1 Show Word on Board"))
        self.pushButton_22.setText(_translate("MainWindow", "2.2 Show Word Vertically"))

        self.groupBox_3.setTitle(_translate("MainWindow", "3. Stereo Disparity Map"))
        self.pushButton_31.setText(_translate("MainWindow", "3.1 Stereo Disparity Map"))

        self.groupBox_4.setTitle(_translate("MainWindow", "4. SIFT"))
        self.pushButton_41.setText(_translate("MainWindow", "Load Image1"))
        self.pushButton_42.setText(_translate("MainWindow", "Load Image2"))
        self.pushButton_43.setText(_translate("MainWindow", "4.1 Keypoints"))
        self.pushButton_44.setText(_translate("MainWindow", "4.2 Matched Keypoints"))

        self.groupBox_5.setTitle(_translate("MainWindow", "5. VGG19"))
        self.pushButton_50.setText(_translate("MainWindow", "Load Image"))
        self.pushButton_51.setText(_translate("MainWindow", "1. Show Augmented Images"))
        self.pushButton_52.setText(_translate("MainWindow", "2. Show Model Structure"))
        self.pushButton_53.setText(_translate("MainWindow", "3. Show Accuracy and Loss"))
        self.pushButton_54.setText(_translate("MainWindow", "4. Inference"))

